# Generated by Django 3.1.6 on 2021-04-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('date', models.DateField()),
                ('state', models.CharField(max_length=20)),
                ('use_elc', models.CharField(max_length=20)),
                ('no_units', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'Details',
            },
        ),
    ]
