# Generated by Django 3.1.6 on 2021-04-22 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elc_bill', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
