# Generated by Django 3.1.6 on 2021-04-22 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elc_bill', '0002_details_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='image',
            field=models.ImageField(default=0, upload_to='pictures'),
            preserve_default=False,
        ),
    ]
