# Generated by Django 3.1.6 on 2021-04-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elc_bill', '0004_auto_20210425_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='state',
            field=models.CharField(choices=[('green', 'GREEN'), ('blue', 'BLUE'), ('red', 'RED'), ('orange', 'ORANGE'), ('black', 'BLACK')], default='green', max_length=20),
        ),
    ]
