# Generated by Django 3.1.6 on 2021-04-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elc_bill', '0008_remove_details_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
    ]
