# Generated by Django 3.1.6 on 2021-04-25 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elc_bill', '0009_auto_20210425_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='gender',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='details',
            name='use_elc',
            field=models.CharField(max_length=70),
        ),
    ]
