# Generated by Django 3.1.6 on 2021-04-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elc_bill', '0011_details_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='use_elc',
        ),
        migrations.AddField(
            model_name='details',
            name='download_pdf',
            field=models.BooleanField(default=False, verbose_name='Do you want to download the pdf'),
        ),
        migrations.AlterField(
            model_name='details',
            name='state',
            field=models.CharField(choices=[('telangana', 'Telangana'), ('delhi', 'Delhi'), ('goa', 'Goa'), ('kerala', 'Kerala')], default='telangana', max_length=30),
        ),
    ]
